### ISSUE TITLE
Pasantía

### ISSUE THREAD

**Issue by rood8592** [pdepjm/2023-tp0-presentacion-MartuRoldan#2]
¿Hace cuanto empezaste a hacer la pasantía y que tipos de tareas realizas?

**Comment by MartuRoldan** [comment]
Hola! La pasantía la arranqué a fin del año pasado. 
Lo que hacemos es utilizar odoo (una ERP del estilo de SAP) para manejar toda la contabilidad, ventas, compras, paginas, etc de nuestros clientes. Lo que yo hago es darles soporte en las modificaciones, consultas o problemas que tengan con el sistema
