### ISSUE TITLE
curso de java

### ISSUE THREAD

**Issue by BritosAylen** [pdepjm/2023-tp0-presentacion-MartuRoldan#3]
Que piola que estés con java back-end, es dificil? Como lo llevas?

**Comment by MartuRoldan** [comment]
Hola! Por ahora bastante bien, son 3 etapas. Hace poco terminó la 1era donde vimos todos los temas más básicos, muy simple, pero la semana que viene arranca la 2da etapa que dijeron que es más complicada 
espero no perderle el ritmo ahora que también estoy con la facu jaja
